parent_dir = "C:\\Users\\daisl\\Desktop\\tab-ddpm-main\\exp_imbalanced_min\\kddcup-guess_passwd_vs_satan_min\\ctabgan"
real_data_path = "C:\\Users\\daisl\\Desktop\\tab-ddpm-main\\data_imbalanced_min\\kddcup-guess_passwd_vs_satan_min"
device = "cpu"
seed = 0

[train_params]
batch_size = 31

[sample]
num_samples = 2000
seed = 0
