parent_dir = "C:\\Users\\daisl\\Desktop\\syrfd\\tab-ddpm-main\\exp_imbalanced\\abalone9-18\\tvae"
real_data_path = "C:\\Users\\daisl\\Desktop\\syrfd\\tab-ddpm-main\\data_imbalanced\\abalone9-18"
device = "cpu"
seed = 0

[train_params]
batch_size = 438

[sample]
num_samples = 438
seed = 0
