parent_dir = "C:\\Users\\daisl\\Desktop\\syrfd\\tab-ddpm-main\\exp_imbalanced\\page-blocks-1-3_vs_4\\ctabganp"
real_data_path = "C:\\Users\\daisl\\Desktop\\syrfd\\tab-ddpm-main\\data_imbalanced\\page-blocks-1-3_vs_4"
device = "cpu"
seed = 0

[train_params]
batch_size = 282

[sample]
num_samples = 282
seed = 0
