parent_dir = "C:\\Users\\daisl\\Desktop\\tab-ddpm-main\\exp_imbalanced_min\\newthyroid2_min\\tvae"
real_data_path = "C:\\Users\\daisl\\Desktop\\tab-ddpm-main\\data_imbalanced_min\\newthyroid2_min"
device = "cpu"
seed = 0

[train_params]
batch_size = 21

[sample]
num_samples = 2000
seed = 0
