parent_dir = "C:\\Users\\daisl\\Desktop\\syrfd\\tab-ddpm-main\\exp_imbalanced\\transfusion\\ctabganp"
real_data_path = "C:\\Users\\daisl\\Desktop\\syrfd\\tab-ddpm-main\\data_imbalanced\\transfusion"
device = "cpu"
seed = 0

[train_params]
batch_size = 448

[sample]
num_samples = 448
seed = 0
