parent_dir = "C:\\Users\\daisl\\Desktop\\syrfd\\tab-ddpm-main\\exp_imbalanced\\pima\\tvae"
real_data_path = "C:\\Users\\daisl\\Desktop\\syrfd\\tab-ddpm-main\\data_imbalanced\\pima"
device = "cpu"
seed = 0

[train_params]
batch_size = 460

[sample]
num_samples = 460
seed = 0
