parent_dir = "C:\\Users\\daisl\\Desktop\\syrfd\\tab-ddpm-main\\exp_imbalanced\\dermatology-6\\ctabganp"
real_data_path = "C:\\Users\\daisl\\Desktop\\syrfd\\tab-ddpm-main\\data_imbalanced\\dermatology-6"
device = "cpu"
seed = 0

[train_params]
batch_size = 214

[sample]
num_samples = 214
seed = 0
