parent_dir = "C:\\Users\\daisl\\Desktop\\tab-ddpm-main\\exp_imbalanced_min\\abalone9-18_min\\ctabgan"
real_data_path = "C:\\Users\\daisl\\Desktop\\tab-ddpm-main\\data_imbalanced_min\\abalone9-18_min"
device = "cpu"
seed = 0

[train_params]
batch_size = 25

[sample]
num_samples = 2000
seed = 0
