parent_dir = "C:\\Users\\daisl\\Desktop\\syrfd\\tab-ddpm-main\\exp_imbalanced\\Migraine_onevsrest_4\\ctabgan"
real_data_path = "C:\\Users\\daisl\\Desktop\\syrfd\\tab-ddpm-main\\data_imbalanced\\Migraine_onevsrest_4"
device = "cpu"
seed = 0

[train_params]
batch_size = 226

[sample]
num_samples = 226
seed = 0
