parent_dir = "C:\\Users\\daisl\\Desktop\\syrfd\\tab-ddpm-main\\exp_imbalanced\\kddcup-guess_passwd_vs_satan\\tvae"
real_data_path = "C:\\Users\\daisl\\Desktop\\syrfd\\tab-ddpm-main\\data_imbalanced\\kddcup-guess_passwd_vs_satan"
device = "cpu"
seed = 0

[train_params]
batch_size = 512

[sample]
num_samples = 984
seed = 0
